import "./globals.css";
import Nav from "./components/Nav";

import { Bangers, Quicksand, Roboto_Condensed } from "next/font/google";
import CartMobileIcon from "./components/CartMobileIcon";
import CartProvider from "./context/CartContext";
import CartMobile from "./components/CartMobile";
import Footer from "./components/Footer";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

const bangers = Bangers({
  subsets: ["latin"],
  variable: "--font-bangers",
  weight: ["400"],
});

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  variable: "--font-robotoCondensed",
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Heyine Burger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>
      <html
        lang="en"
        className=" scrollbar-thin scrollbar-track-slate-300 scrollbar-thumb-secondary"
      >
        <body
          className={`${quicksand.variable} ${bangers.variable} ${robotoCondensed.variable} font-quicksand`}
        >
          <Nav />
          <CartMobileIcon />
          <CartMobile />
          {children}
          <Footer />
        </body>
      </html>
    </CartProvider>
  );
}
